spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.company.service

server:
  port: 29263

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 10.9.42.203:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-company-es-group-dev

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: COMPANY-INFO
  companyinfo:
    topic:company-company-info-dev-203
metadata:
  broker:
    list:10.9.42.203:9092
request:
  required:
    acks:0

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://10.9.42.203:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://10.9.42.203:8087/security/users/password.update
  
loginOauth2:
  endpoint: http://10.9.42.203:8087/security/oauth/accesstoken

---

spring:
  profiles: qa

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.company.service

server:
  port: 19216

cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_qa

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-qa
  host: 172.28.24.32
  port: 9301
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 172.28.24.32:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-company-es-group-qa

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: COMPANY-INFO
  companyinfo:
    topic: company-company-info-qa-32
metadata:
  broker:
    list: 172.28.24.32:9092
request:
  required:
    acks: 0

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s

userRegister:
  endpoint:  http://172.28.24.32:19301/security/guanhutong3g/register

oauth2:
  updatepassword:  http://172.28.24.32:19301/security/users/password.update
  
loginOauth2:
  endpoint:  http://172.28.24.32:19301/security/oauth/accesstoken
    
---

spring:
  profiles: product
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://103.245.128.220:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.company.service

server:
  port: 39001

cassandra:
  contactpoints: 120.24.169.69
  port: 9042
  keyspace: pois_qa

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit_qa
  host: 172.28.4.220
  port: 9301
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 120.24.169.69:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-company-es-group-qa

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: COMPANY-INFO
  companyinfo:
    topic:company-company-info-dev-203
metadata:
  broker:
    list:10.9.42.203:9092
request:
  required:
    acks:0

checkToken:
  endpoint: http://120.24.169.69:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://120.24.169.69:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://120.24.169.69:8087/security/users/password.update
  
loginOauth2:
  endpoint: http://120.24.169.69:8087/security/oauth/accesstoken
