spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.company.search.service

server:
  port: 29363

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 10.9.42.203:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-company-es-group-dev-203

auto:
  commit:
    interval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  companyinfo:
    topic: company-company-info-dev-203
  companywithproduct:
    topic: company-companywithproduct-info-dev-203
  companywithproductprice:
    topic: company-companywithproductprice-info-dev-203
  consumer:
    thread:
      num: 5

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://10.9.42.203:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://10.9.42.203:8087/security/users/password.update
  
loginOauth2:
  endpoint: http://10.9.42.203:8087/security/oauth/accesstoken

---

spring:
  profiles: qa

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.company.service

server:
  port: 19316

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 172.28.24.32
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 172.28.24.32:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-company-es-group-qa-32

auto:
  commit:
    interval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  companyinfo:
    topic: company-company-info-qa-32
  companywithproduct:
    topic: company-companywithproduct-info-qa-32
  companywithproductprice:
    topic: company-companywithproductprice-info-qa-32
  consumer:
    thread:
      num: 5

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s

userRegister:
  endpoint:  http://172.28.24.32:19301/security/guanhutong3g/register

oauth2:
  updatepassword:  http://172.28.24.32:19301/security/users/password.update
  
loginOauth2:
  endpoint:  http://172.28.24.32:19301/security/oauth/accesstoken
    
---

spring:
  profiles: product
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://103.245.128.220:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.company.service

server:
  port: 39001

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 172.28.24.32
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 172.28.24.32:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-company-es-group-qa-32

auto:
  commit:
    interval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  companyinfo:
    topic: company-company-info-qa-32
  companywithproduct:
    topic: company-companywithproduct-info-qa-32
  companywithproductprice:
    topic: company-companywithproductprice-info-qa-32
  consumer:
    thread:
      num: 5

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s

userRegister:
  endpoint:  http://172.28.24.32:19301/security/guanhutong3g/register

oauth2:
  updatepassword:  http://172.28.24.32:19301/security/users/password.update
  
loginOauth2:
  endpoint:  http://172.28.24.32:19301/security/oauth/accesstoken
