spring:
  profiles: qa
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.userlocationsearch.service
#tomcat
server:
  port: 19223
  context-path: /userlocationserver

cassandra:
  contactpoints: localhost
  port: 9042
  keyspace: pois
#endpoints
checkToken:
  endpoint: http://localhost:19301/security/oauth/check_token?token=%s
#health
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true


#otherServerAddress
oauth2Server:
  address: http://localhost:19301/security/users
oauth2ServerByMyInfo:
  address: http://localhost:19301/security/users/myInfo
oauth2ServerByUser:
  address: http://localhost:19301/security/users
oauth2ServerByLoginName:
  address: http://localhost:19301/security/users/userInfo
oauth2ServerByToken:
  address: http://localhost:19301/security/oauth/accesstoken
#elasticsearch
elasticsearch:
  clusterName: changhongit
  host: 192.168.191.50
  port: 9301
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

zookeeper: 
  connect: localhost:2181
  session: 
    timeout: 
      ms: 14000
  sync: 
    time: 
      ms: 200
auto: 
  commit: 
    interval: 
      ms: 1000
group:
  id: changhongit-es-group
topic: user-location-updater
numThreads: 8

loginName: sys
password: sys
