spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.pois.service

server:
  port: 29262

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit_dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 10.9.42.203:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-pois-es-group-dev

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: POIS-INFO

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://10.9.42.203:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://10.9.42.203:8087/security/users/password.update
  
loginOauth2:
  endpoint: http://10.9.42.203:8087/security/oauth/accesstoken

companyServer:
  address: http://10.9.42.203:8087/companies
  
employeeServer:
  address: http://10.9.42.203:8087/employees/byloginid

chitpois:
  address: http://10.9.42.203:8087/chitpois/poi

mail:
  from: 3245335402@qq.com  
  host: smtp.qq.com
  username: 3245335402   
  password: changhongit2014 
  defaultEncoding: UTF-8	 
  smtp:
    auth: true  
    timeout: 25000  
  transport:
    protocol: smtp  

---

spring:
  profiles: qa

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.pois.service

server:
  port: 19215

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true


cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_qa


elasticsearch:
  clusterName: changhongit-qa
  host: 172.28.24.32
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 172.28.24.32:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-pois-es-group-qa

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  topic: POIS-INFO

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://172.28.24.32:19301/security/guanhutong3g/register
  
loginOauth2:
  endpoint: http://172.28.24.32:19301/security/oauth/accesstoken
  

companyServer:
  address: http://172.28.24.32:19301/companies
  
employeeServer:
  address: http://172.28.24.32:19301/employees/byloginid

chitpois:
  address: http://172.28.24.32:19301/chitpois/poi

mail:
  from: 3245335402@qq.com  
  host: smtp.qq.com
  username: 3245335402   
  password: changhongit2014 
  defaultEncoding: UTF-8	 
  smtp:
    auth: true  
    timeout: 25000  
  transport:
    protocol: smtp  
 
    
---

spring:
  profiles: product
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://103.245.128.220:8087/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.pois.service

server:
  port: 39002

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true


cassandra:
  contactpoints: 120.24.169.69
  port: 9042
  keyspace: pois_qa

checkToken:
  endpoint: http://120.24.169.69:8087/security/oauth/check_token?token=%s
  
userRegister:
  endpoint: http://172.28.4.220:8087/security/guanhutong3g/register  

loginOauth2:
  endpoint: http://120.24.169.69:8087/security/oauth/accesstoken
  

companyServer:
  address: http://120.24.169.69:8087/companies
  
employeeServer:
  address: http://120.24.169.69:8087/employees/byloginid

chitpois:
  address: http://120.24.169.69:8087/chitpois/poi

mail:
  from: 3245335402@qq.com  
  host: smtp.qq.com
  username: 3245335402   
  password: changhongit2014 
  defaultEncoding: UTF-8	 
  smtp:
    auth: true  
    timeout: 25000  
  transport:
    protocol: smtp  
