spring:
  profiles: dev


eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.poiweb.service

server:
  port: 29265
  context-path: /chitpois

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

checkToken:
  endpoint: http://10.9.42.203:8086/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://10.9.42.203:8086/security/guanhutong3g/register

oauth2:
  updatepassword: http://10.9.42.203:8086/security/users/password.update
  
loginOauth2:
  endpoint: http://10.9.42.203:8086/security/oauth/accesstoken

login:
  endpoint: http://10.9.42.203:8087/security/oauth/authorize?response_type=code&client_id=webApp&redirect_uri=http://10.9.42.203:29265/poi-web/loading

token:
  endpoint: http://10.9.42.203:8087/security/oauth/token?code=%s&grant_type=authorization_code&redirect_uri=http://10.9.42.203:29265/poi-web/loading

logout:
  endpoint: http://10.9.42.203:8087/security/logout?redirect_url=http://10.9.42.203:8086/chitpois

companyServer:
  address:http://10.9.42.203:8087/companies
  
employeeServer:
  address: http://10.9.42.203:8087/employees/byloginid 
 
chitpois:
  address: http://10.9.42.203:8087/chitpois/poi 
   
---

spring:
  profiles: qa

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.28.4.220:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.poiweb.service

server:
  port: 19214
  context-path: /chitpois
cassandra:
  contactpoints: 172.28.4.220
  port: 9042
  keyspace: pois_qa




checkToken:
  endpoint: http://172.28.4.220:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://172.28.4.220:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://172.28.4.220:8087/security/users/password.update
  
loginOauth2:
  endpoint: http://172.28.4.220:8087/security/oauth/accesstoken

login:
  endpoint: http://172.28.4.220:8087/security/oauth/authorize?response_type=code&client_id=webApp&redirect_uri=http://10.9.42.203:29265/poi-web/loading

token:
  endpoint: http://172.28.4.220:8087/security/oauth/token?code=%s&grant_type=authorization_code&redirect_uri=http://10.9.42.203:29265/poi-web/loading

logout:
  endpoint: http://172.28.4.220:8087/security/logout?redirect_url=http://10.9.42.203:8086/chitpois

companyServer:
  address:http://172.28.4.220:8087/companies
  
employeeServer:
  address: http://10.9.42.203:8087/employees/byloginid 
 
chitpois:
  address: http://10.9.42.203:8087/chitpois/poi 
  
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
    
---

spring:
  profiles: product
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://103.245.128.220:8087/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.poiweb.service

server:
  port: 39003
  context-path: /chitpois
cassandra:
  contactpoints: 120.24.169.69
  port: 9042
  keyspace: pois_qa


checkToken:
  endpoint: http://120.24.169.69:8087/security/oauth/check_token?token=%s

userRegister:
  endpoint: http://120.24.169.69:8087/security/guanhutong3g/register

oauth2:
  updatepassword: http://120.24.169.69:8087/security/users/password.update
  
loginOauth2:
  endpoint: http://120.24.169.69:8087/security/oauth/accesstoken

login:
  endpoint: http://120.24.169.69:8087/security/oauth/authorize?response_type=code&client_id=webApp&redirect_uri=http://10.9.42.203:29265/poi-web/loading

token:
  endpoint: http://120.24.169.69:8087/security/oauth/token?code=%s&grant_type=authorization_code&redirect_uri=http://10.9.42.203:29265/poi-web/loading

logout:
  endpoint: http://120.24.169.69:8087/security/logout?redirect_url=http://10.9.42.203:8086/chitpois

companyServer:
  address:http://120.24.169.69:8087/companies
  
employeeServer:
  address: http://120.24.169.69:8087/employees/byloginid 
 
chitpois:
  address: http://120.24.169.69:8087/chitpois/poi 
  
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
