spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.productprice.search.service

server:
  port: 29369

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 10.9.42.203:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-es-productprice-group-dev-203

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  productprice:
    topic: productprice-productprice-info-dev-203
  consumer:
    thread:
      num:5

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s

---

spring:
  profiles: qa
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 19325

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-qa
  host: 172.28.24.32
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
zookeeper:
  connect: 172.28.24.32:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

group:
  id: changhongit-es-productprice-group-qa-32

auto:
  commit:
    nterval:
      ms: 1000
  offset:
    reset: smallest

kafka:
  productprice:
    topic: productprice-productprice-info-qa-32
  consumer:
    thread:
      num:5

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s