spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.4.220:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.productprice.location.service

server:
  port: 29276

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit_dev
  host: 172.28.4.220
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
group:
  id: changhongit-productprice-es-group-dev
zookeeper:
  connect: 172.28.4.220:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200
auto:
  commit:
    interval:
      ms: 1000
  offset:
    reset: smallest
kafka:
  topic: PRODUCTPRICE-INFO

---

spring:
  profiles: qa

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.4.220:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.productprice.location.service

server:
  port: 19265

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit_qa
  host: 172.28.4.220
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
group:
  id: changhongit-productprice-es-group-dev
zookeeper:
  connect: 172.28.4.220:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200
auto:
  commit:
    interval:
      ms: 1000
  offset:
    reset: smallest
kafka:
  topic: PRODUCTPRICE-INFO