spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.productprice.service

server:
  port: 29269

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit-dev
  host: 10.9.42.203
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
kafka:
  topic: PRODUCTPRICE-INFO
  productprice:
    topic: productprice-productprice-info-dev-203
  companywithproductprice:
    topic: company-companywithproductprice-info-dev-203
metadata:
    broker:
      list: 10.9.42.203:9092
request:
  required:
    acks: 0
checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s

getToken:
  endpoint: http://10.9.42.203:8087/security/oauth/accesstoken
 
companyServer:
  address: http://10.9.42.203:8087/companies/{uuid}
  add:
    address: http://10.9.42.203:8087/companies

productServer:
  address: http://172.28.4.220:8086/products/{uuid}
  add:
    address: http://172.28.4.220:8086/products

---

spring:
  profiles: qa
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 19225

cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_qa

#kafka
kafka:
  topic: PRODUCTPRICE-INFO
  productprice:
    topic: productprice-productprice-info-qa-32
  companywithproductprice:
    topic: company-companywithproductprice-info-qa-32
metadata:
  broker:
    list: 172.28.24.32:9092
request:
  required:
    acks: 0

elasticsearch:
  clusterName: changhongit-qa
  host: 172.28.24.32
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s

getToken:
  endpoint: http://172.28.24.32:19301/security/oauth/accesstoken
 
companyServer:
  address: http://172.28.24.34:19216/companies/{uuid}
  add:
    address: http://172.28.24.34:19216/companies

productServer:
  address: http://172.28.24.34:19224/products/{uuid}
  add:
    address: http://172.28.24.34:19224/products

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true