spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.4.220:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 29267

cassandra:
  contactpoints: 172.28.4.220
  port: 9042
  keyspace: pois_dev

checkToken:
  endpoint: http://172.28.4.220:8086/security/oauth/check_token?token=%s
companydetail:
  points: http://172.28.4.220:8086/companies/{uuid}

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

---

spring:
  profiles: qa
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.4.220:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 19224

cassandra:
  contactpoints: 172.28.4.220
  port: 9042
  keyspace: pois_qa

checkToken:
  endpoint: http://172.28.4.220:8087/security/oauth/check_token?token=%s
companydetail:
  points: http://172.28.4.220:8087/companies/{uuid}

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true