spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.4.220:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.productprice.service

server:
  port: 29269

cassandra:
  contactpoints: 172.28.4.220
  port: 9042
  keyspace: pois_dev

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

elasticsearch:
  clusterName: changhongit_dev
  host: 172.28.4.220
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

#kafka
kafka:
  topic: PRODUCTPRICE-INFO
  metadata:
    broker:
      list: 172.28.4.220:9092

checkToken:
  endpoint: http://172.28.4.220:8086/security/oauth/check_token?token=%s

getToken:
  endpoint: http://172.28.4.220:8086/security/oauth/accesstoken
 
companyServer:
  address: http://172.28.4.220:8086/companies/{uuid}
  add:
    address: http://172.28.4.220:8086/companies

productServer:
  address: http://172.28.4.220:8086/products/{uuid}
  add:
    address: http://172.28.4.220:8086/products

---

spring:
  profiles: qa
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.4.220:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 19225

cassandra:
  contactpoints: 172.28.4.220
  port: 9042
  keyspace: pois_qa

#kafka
kafka:
  topic: PRODUCTPRICE-INFO
  metadata:
    broker:
      list: 172.28.4.220:9092

elasticsearch:
  clusterName: changhongit_dev
  host: 172.28.4.220
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

checkToken:
  endpoint: http://172.28.4.220:8087/security/oauth/check_token?token=%s

getToken:
  endpoint: http://172.28.4.220:8087/security/oauth/accesstoken
 
companyServer:
  address: http://172.28.4.220:19216/companies/{uuid}
  add:
    address: http://172.28.4.220:19216/companies

productServer:
  address: http://172.28.4.220:19224/products/{uuid}
  add:
    address: http://172.28.4.220:19224/products

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true