spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.9.42.203:8087/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 29267

cassandra:
  contactpoints: 10.9.42.203
  port: 9042
  keyspace: pois_dev
#kafka
metadata:
  broker:
    list: 10.9.42.203:9092
kafka:
  companywithproduct:
    topic: company-companywithproduct-info-dev-203
request:
  required:
    acks: 0

checkToken:
  endpoint: http://10.9.42.203:8087/security/oauth/check_token?token=%s
companydetail:
  points: http://localhost:29263/companies/{uuid}

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true

---

spring:
  profiles: qa
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.28.24.32:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.product.service

server:
  port: 19224

cassandra:
  contactpoints: 172.28.24.32
  port: 9042
  keyspace: pois_dev
#kafka
metadata:
  broker:
    list: 172.28.24.32:9092
kafka:
  companywithproduct:
    topic: company-companywithproduct-info-qa-32
request:
  required:
    acks: 0

checkToken:
  endpoint: http://172.28.24.32:19301/security/oauth/check_token?token=%s
companydetail:
  points: http://172.28.24.32:29263/companies/{uuid}

endpoints:
  health:
    id: health
    sensitive: false
    enabled: true