spring:
  profiles: qa
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      virtual-host-name: loving.baidupush.service

server:
  port: 19220
  
cassandra:
  contactpoints: 192.168.191.50
  port: 9042
  keyspace: pois
  
elasticsearch:
  clusterName: changhongit
  host: 192.168.191.50
  port: 9300
  sniff: true
  ignore_cluster_name: false
  ping_timeout: 20s
  nodes_sampler_interval: 20s

endpoints:
  health:
   id: health
   sensitive: false
   enabled: true

group:
  id: changhongit-group
  
#kafka
zookeeper:
  connect: 192.168.191.50:2181
  session:
    timeout:
      ms: 14000
  sync:
    time:
      ms: 200

auto: 
  commit: 
    interval: 
      ms: 1000
      
topic: user-location-updater
numThreads: 8


metadata:
  broker:
    list: 192.168.191.50:9092
request:
  required:
    acks: 0
num:
  partitions: 8
log:
  retention:
    hours: 1

#baidu push
apiKey: 4dWe6R0KzlfHZZdqjUzz6urV
secretKey: B99dOXbY8nDWrqIyKYg72u677jckIPcc

#auto test
checkToken:
  endpoint: http://localhost:19301/security/oauth/check_token?token=%s
oauth2ServerByMyInfo:
  address: http://localhost:19301/security/users/myInfo
oauth2ServerByUser:
  address: http://localhost:19301/security/users
oauth2ServerByToken:
  address: http://localhost:19301/security/oauth/accesstoken
userLocationRestServer:
  address: http://localhost:19301/userlocationserver


loginName: sys
password: sys
