swagger: '2.0'
info:
  title: Book
  description: Move your app forward with the book API 
  version: 1.0.0
host: '103.245.128.220:8087'
schemes:
  - http
produces:
  - application/json
paths:
  /books:
    post:
      summary: 新增图书.    
      description: 新增图书.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookAddRequest
          in: body
          description: 图书信息.
          schema:
            $ref: '#/definitions/bookAddRequest'
          required: true
      tags:
        - 图书
      responses:
        '201':
          description: 新增成功
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  
    get:
      summary: 图书列表.
      description:
        查询图书列表.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
      tags:
        - 图书
      responses:
        '200':
          description: 查询图书列表成功
          schema:
            type: array
            items:
              $ref: '#/definitions/books'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /books/{bookuuid}:
    patch:
      summary: 修改某本图书信息.    
      description: 修改某本图书信息. 
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookUpdateRquest
          in: body
          description: 图书信息.
          schema:
            $ref: '#/definitions/bookUpdateRequest'
          required: true
        - name: bookuuid
          in: path
          type: string
          description: 图书ID.
          required: true
          format: uuid          
      tags:
        - 图书
      responses:
        '200':
          description: 更新图书信息成功
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: 删除某本图书.
      description: 删除某本图书.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookuuid
          in: path
          type: string
          description: 图书ID.
          required: true
          format: uuid
      tags:
        - 图书
      responses:
        '200':
          description: 删除成功
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'            
    get:
      summary: 根据uuid查询书的详细信息.
      description:
        根据uuid查询书的详细信息.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookuuid
          in: path
          type: string
          description: 图书uuid.
          required: true
          format: uuid

      tags:
        - 图书
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/book'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /books/{bookuuid}/chapters:
    post:
      summary:  向某本图书添加章节.
      description: 向某本图书添加章节.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookuuid
          in: path
          type: string
          description: 图书ID.
          required: true
          format: uuid
        - name: chapterAddRequest
          in: body
          description: 图书信息.
          schema:
            $ref: '#/definitions/chapterAddRequest'
          required: true          
      tags:
        - 图书
      responses:
        '201':
          description: 添加图书章节.  
    get:
      summary: 查询某本图书的所有章节信息.
      description: 查询某本图书的所有章节信息.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookuuid
          in: path
          description: 图书uuid.
          required: true
          type: string
          format: double      
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
          format: int
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
          format: int
      tags:
        - 图书 
      responses:
        '200':
          description: 查询某本图书下的所有章节信息成功.
          schema:
            $ref: '#/definitions/chapters'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /books/{bookuuid}/chapters/{chapteruuid}:
    patch:
      summary: 修改某本图书下某章节信息.    
      description: 修改某本图书下某章节信息. 
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: chapterUpdateRquest
          in: body
          description: 图书信息.
          schema:
            $ref: '#/definitions/chapterUpdateRequest'
          required: true
        - name: bookuuid
          in: path
          type: string
          description: 图书ID.
          required: true
          format: uuid          
        - name: chapteruuid
          in: path
          description: 章节ID.
          required: true
          type: string
      tags:
        - 图书
      responses:
        '200':
          description: 更新成功
          
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: 删除某本图书下某章节.
      description: 删除某本图书下某章节.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookuuid
          in: path
          type: string
          description: 图书ID.
          required: true
          format: uuid
        - name: chapteruuid
          in: path
          description: 章节ID.
          required: true
          type: string
      tags:
        - 图书
      responses:
        '200':
          description: 删除成功
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'            
    get:
      summary: 查询某本图书某章节的信息.
      description: 查询某本图书某章节的信息.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: bookuuid
          in: path
          description: 图书ID.
          required: true
          type: string
        - name: chapteruuid
          in: path
          description: 章节ID.
          required: true
          type: string
      tags:
        - 图书 
      responses:
        '200':
          description: 查询成功.
          schema:
            $ref: '#/definitions/chapters_content'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'   
            
           
definitions:
  books:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: 获取下一页数据的url.
          self:
            properties:
              href:
                type: string
                description: 获取当前页数据的url.
          prev:
            properties:
              href:
                type: string
                description: 获取上一页数据的url.
      _embedded:
        properties:
          booksResponses:
            type: array
            items:
              $ref: '#/definitions/books_content'
      page:
        properties:
          size:
            type: string
            description: 每页显示多少条
          totalElements:
            type: string
            description: 总共多少条数据
          totalPages:
            type: string
            description: 总共多少页
          number:
            type: string
            description: 当前第几页 

  books_content:
    properties:
      title:
        type: string
        description:  书名.
      preface:
        type: string
        description:  前言.
      numberOfPages:
        type: string
        description:  书总页数.
      cover_img_link:
        type: string
        description:  书封面图片链接.      
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: 获取当前书信息的url链接.
  book:
    properties:
      title:
        type: string
        description:  书名.
      preface:
        type: string
        description:  前言.
      numberOfPages:
        type: string
        description:  书总页数.
      coverImgUrl:
        type: string
        description:  书封面图片链接.      
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: 获取当前书信息的url链接.
      chapters_link:
        type: string
        description: 获取当前图书所有章节的url链接.

  bookUpdateRequest:
    properties:
      title:
        type: string
        description:  书名.
      preface:
        type: string
        description:  前言.
      author:
        type: string
        description:  作者.
      categoryCode:
        type: string
        description:  分类编码.
      categoryCodeDesc:
        type: string
        description:  分类描述.
      releaseStatus:
        type: string
        description:  上架状态.
      coverImgUrl:
        type: string
        description:  封面图片链接.  
      remark:
        type: string
        description:  备注.  

  bookAddRequest:
    properties:
      title:
        type: string
        description:  书名.
      preface:
        type: string
        description:  前言.
      author:
        type: string
        description:  作者.
      categoryCode:
        type: string
        description:  分类编码.
      categoryCodeDesc:
        type: string
        description:  分类描述.
      releaseStatus:
        type: string
        description:  上架状态.
      coverImgUrl:
        type: string
        description:  封面图片链接.  
      remark:
        type: string
        description:  备注.  
        
  chapters:
    properties:
      numberOfChapters:
        type: string
        description: 总章节数.
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: 获取下一页数据url.
          self:
            properties:
              href:
                type: string
                description: 获取当前页数据url.
          prev:
            properties:
              href:
                type: string
                description: 获取上一页数据url.
      _embedded:
        properties:
          chaptersResponses:
            type: array
            items:
              $ref: '#/definitions/chapters_content'
      page:
        properties:
          size:
            type: string
            description: 每页显示多少条
          totalElements:
            type: string
            description: 总共多少条数据
          totalPages:
            type: string
            description: 总共多少页
          number:
            type: string
            description: 当前第几页 
            
  chapters_content:
    properties:
      title:
        type: string
        description:  章节标题.
      numberOfPages:
        type: string
        description:  章节总共页数.
      pages_link:
        type: string
        description:  获取章节下所有页数据的url.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: 获取当前章节信息的url.
 
  chapterAddRequest:
    properties:
      title:
        type: string
        description:  章节标题.

  chapterUpdateRequest:
    properties:
      title:
        type: string
        description:  章节标题.
                
  pages:
    properties:
      numberOfPages:
        type: string
        description: 总页数.
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: 获取下一页数据url.
          self:
            properties:
              href:
                type: string
                description: 获取当前页数据url.
          prev:
            properties:
              href:
                type: string
                description: 获取上一页数据url.
      _embedded:
        properties:
          pagesResponses:
            type: array
            items:
              $ref: '#/definitions/pages_content'
              
  pages_content:
    properties: 
      pageNo:
        type: string
        description:  当前页号.
      page_link:
        type: string
        description:  获取当前页相信信息的url.
  pageAddRequest:
    properties: 
      pageNo:
        type: string
        description:  当前页号.
      paragraphs:
        type: array
        items:
          $ref: '#/definitions/paragraph'      
  pageUpdateRequest:
    properties: 
      pageNo:
        type: string
        description:  当前页号.
      paragraphs:
        type: array
        items:
          $ref: '#/definitions/paragraph'   
  page:
    properties:
      paragraphs:
        properties:
          paragraphsResponses:
            type: array
            items:
              $ref: '#/definitions/paragraphs_content'
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: 获取下一页数据url.
          self:
            properties:
              href:
                type: string
                description: 获取当前页数据url.
          prev:
            properties:
              href:
                type: string
                description: 获取上一页数据url.
  paragraphs_content:
    properties: 
      type:
        type: string
        description:  段落类型(如:image、text).
      content:
        type: string
        description:  段落内容(如果type类型为image则返回图片的url链接,否则type类型为txt为文本内容).
  paragraph:
    properties: 
      type:
        type: string
        description:  段落类型(如:image、text).
      content:
        type: string
        description:  段落内容(如果type类型为image则返回图片的url链接,否则type类型为txt为文本内容).
  
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
