swagger: '2.0'
info:
  title: orders
  description: 订单服务API 
  version: 1.0.0
host: '10.9.42.203:8087'
schemes:
  - http
produces:
  - application/json
paths:
  /companies/{uuid}/orders:
    post:
      summary: 创建订单API.
      description:
        创建订单API.
      parameters:
        - name: uuid
          in: path
          type: string
          description: uuid.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: cart
          in: body
          description: 创建订单body.
          schema:
             $ref: '#/definitions/orderAddRequest'
          required: true
      tags:
        - 订单服务
      responses:
        '201':
          description: 创建订单成功.
          
    get:
      summary: 查找服务商订单列表API.
      description:
        查找服务商订单列表API.
      parameters:
        - name: uuid
          in: path
          type: string
          description: uuid.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 订单服务
      responses:
        '200':
          description: 查找服务商订单列表成功.
          schema:
            $ref: '#/definitions/orders'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'           
          
  /orders/{uuid}:
    get:
      summary: 查询订单详情API.
      description:
        查询订单详情API.
      parameters:
        - name: uuid
          in: path
          type: string
          description: uuid.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 订单服务
      responses:
        '200':
          description: 查询订单详情成功.
          schema:
            $ref: '#/definitions/getOrder'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    patch:
      summary: 修改订单状态API.
      description:
        修改订单状态API.
      consumes:
        - application/vnd.jiahua.commands.updatestatus+json
      parameters:
        - name: uuid
          in: path
          type: string
          description: uuid.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: cartRequest
          in: body
          description: 修改订单状态body.
          schema:
            $ref: '#/definitions/orderRequest'
          required: true
      tags:
        - 订单服务
      responses:
        '200':
          description: 订单服务成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /orders:
   get:
      summary: 查找所有订单列表API.
      description:
        查找所有订单列表API.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 订单服务
      responses:
        '200':
          description: 查找所有订单列表成功.
          schema:
            $ref: '#/definitions/orders'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error' 
  /orders/{uuid}/items:
    get:
      summary: 查询订单服务项目API.
      description:
        查询订单服务项目API.
      parameters:
        - name: uuid
          in: path
          type: string
          description: uuid.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 订单服务
      responses:
        '200':
          description: 查询订单服务项目成功.
          schema:
            $ref: '#/definitions/items'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:  
  orderAddRequest:
    properties:
        customerId:
          type: string
          description: 客户ID.
        shippingAddress:
          description: 送货地址.
          type: object
          properties:
            address:
              type: string
              description: 服务地址.
            tel:
              type: string
              description: 联系电话.
            name:
              type: string
              description: 用户姓名.
        comment:
          type: string
          description: 描述.
        serviceTime:
          type: string
          description: 服务时间.
        items:
          description: 服务项目列表.
          type: array
          items:
            $ref: '#/definitions/item'
        detail:
          type: object
          description: 详情.
  item:
    properties:
      uuid:
        type: string
        description: 服务项目编号.
      amount:
        type: string
        description: 数量.
  orderRequest:
    properties:
        currentStatus:
            type: string
            description: 订单状态.
        comment:
            type: string
            description: 描述.
  orders:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        properties:
          orderResponses:
            type: array
            items:
              $ref: '#/definitions/getOrder'
      page:
        properties:
          size:
            type: integer
            description: page size
          totalElements:
            type: integer
            description: data total
          totalPages:
            type: integer
            description: page total
          number:
            type: integer
            description: current page 
  getOrder:
    properties:
        uuid:
          type: string
          description: 订单编号.
        orderId:
          type: string
          description: 订单流水号.
        customer:
          type: object
          description: 顾客.
          properties:
            uuid:
              type: string
              description: uuid.
            name:
              type: string
              description: 姓名.
            tel:
              type: string
              description: 电话.
            sex:
              type: string
              description: 性别.
            self:
              properties:
                href:
                  type: string
                  description: self. 
                  
        company:
            type: object
            description: 服务商.
            properties:
              uuid:
                type: string
                description: uuid.
              name:
                type: string
                description: 姓名.
              tel:
                type: string
                description: 电话.
              sex:
                type: string
                description: 性别.
              address:
                type: string
                description: 地址. 
              self:
                properties:
                  href:
                    type: string
                    description: self. 
        currentStatus:            
            type: string
            description: 服务状态.
        shippingAddress:
          description: 送货地址.
          type: object
          properties:
            address:
              type: string
              description: 服务地址.
            tel:
              type: string
              description: 联系电话.
            name:
              type: string
              description: 用户姓名.
        comment:
          type: string
          description: 描述.
        serviceTime:
          type: string
          description: 服务时间.
        creater:
          description: 创建者.
          type: object
          properties:
            uuid:
              type: string
              description: uuid.
            name:
              type: string
              description: 姓名.
            self:
              properties:
                href:
                  type: string
                  description: self. 
        detail:
          type: object
          description: 详情.   
        _links:
          properties:
            shippingInfo:
              properties:
                href:
                  type: string
                  description: orders/{uuid}/shippinginfo. 
            items:
              properties:
                href:
                  type: string
                  description: orders/{uuid}/items. 
            feedback:
              properties:
                href:
                  type: string
                  description: orders/{uuid}/feedback. 
  items:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        properties:
          itemsResponses:
            type: array
            items:
              $ref: '#/definitions/getItems'
      page:
        properties:
          size:
            type: integer
            description: page size
          totalElements:
            type: integer
            description: data total
          totalPages:
            type: integer
            description: page total
          number:
            type: integer
            description: current page    
            
  getItems:
    properties:
        productPriceUuid:
            type: string
            description: 产品价格ID.
        name:
            type: string
            description: 名称.
        price:
          type: number
          description: 单价.
        unit:
          type: string
          description: 单位.
        amount:
          type: integer
          description: 数量. 
        subtotal:
          type: number
          description: 小计.
        _links:
          properties:
            self:
              properties:
                href:
                  type: string
                  description: self. 
            
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string