swagger: '2.0'
info:
  title: Product Price
  description: Product price application API 
  version: 1.0.0
host: '103.245.128.220:8087'
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /productprices/search:
    get:
      summary: 查询产品价格服务.
      description: 多条件查询产品价格服务.
      parameters:
        - name: keyword
          in: query
          description: 产品名称(productName)查询,支持模糊查询.
          required: false
          type: string
        - name: catgoryId
          in: query
          description: 根据产品价格分类查询.
          required: false
          type: string
        - name: productCategoryId
          in: query
          description: 根据产品分类查询.
          required: false
          type: string
        - name: productId
          in: query
          description: 根据产品Id查询.
          required: false
          type: string
        - name: bevel
          in: query
          default: 5
          description: 位置直径(单位为公里,默认是5公里).
          required: false
          type: string
          format: double
        - name: lat
          in: query
          description: 地理位置查询(中心点的纬度).
          required: true
          type: string
          format: double
        - name: lon
          in: query
          description: 地理位置查询(中心点的经度).
          required: true
          type: string
          format: double
      tags:
        - 多条件查询
      responses:
        '201':
          description: 查询成功.
          schema:
            type: string
           
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
  /productprices/search/products:
    post:
      summary: 查询产品服务价格并根据产品分组.
      description: 查询产品服务价格并根据产品分组.
      parameters:
        - name: keyword
          in: query
          description: 产品名称(productName)查询,支持模糊查询.
          required: false
          type: string
        - name: catgoryId
          in: query
          description: 根据产品价格分类查询.
          required: false
          type: string
        - name: productCategoryId
          in: query
          description: 根据产品分类查询.
          required: false
          type: string
        - name: bevel
          in: query
          default: 5
          description: 位置直径(单位为公里,默认是5公里).
          required: false
          type: string
          format: double
        - name: lat
          in: query
          description: 地理位置查询(中心点的纬度).
          required: true
          type: string
          format: double
        - name: lon
          in: query
          description: 地理位置查询(中心点的经度).
          required: true
          type: string
          format: double
      tags:
        - 多条件查询(按产品分组)
      responses:
        '201':
          description: 查询成功.
          schema:
            type: string
           
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
            
  /productprices:
    post:
      summary: 增加一个产品价格服务
      description: 新增产品价格服务
      parameters:
        - name: addproductprice
          in: body
          description: The productPrice JSON you want to post
          schema:
            $ref: '#/definitions/addproductprice'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: X-Token is a request header and is required.
          required: true
          type: string
      tags:
        - 新增产品价格服务
      responses:
        '200':
          description: 添加成功
    get:
      summary: 查询产品服务列表
      description: 查询产品服务列表.
      parameters:
        - name: page
          in: query
          default: 0
          description: 分页参数
          required: false
          type: number
          format: int
        - name: size
          in: query
          default: 20
          description: 每页的数量(默认20)
          required: false
          type: number
          format: int
        - name: nextId
          in: query
          description: 下一页ID
          required: false
          type: string
        - name: previousId
          in: query
          description: 上一页ID.
          required: false
          type: string
      tags:
        - productprices
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/productprices'
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
  '/productprices/{id}':
    get:
      summary: 根据ID查询产品服务
      description: 根据ID查询产品服务
      parameters:
        - name: id
          in: path
          type: string
          description: 产品服务ID
          required: true
          format: uuid
      tags:
        - productprices    
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/productpriceByIdResponse'
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'      
    patch:
      summary: 修改产品服务
      description: 修改产品服务
      parameters:
        - name: id
          in: path
          description: 产品服务ID
          required: true
          type: string
          format: uuid
        - name: updateproductprice
          in: body
          description: 可以修改的参数,在request body中
          schema:
            $ref: '#/definitions/updateproductprice'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true
          type: string 
      tags:
        - productprices    
      responses:
        '200':
          description: 修改成功
        default:
          description: 修改失败
          schema:
            $ref: '#/definitions/Error'  
    delete:
      summary: 删除产品价格
      description: 删除产品价格
      parameters:
        - name: id
          in: path
          description: 产品价格ID
          required: true
          type: string
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true
          type: string
      tags:
        - productprices  
      responses:
        '200':
          description: 删除成功
        default:
          description: 删除失败
          schema:
            $ref: '#/definitions/Error'
  /ppcategories:
    post:
      summary: 新增产品价格类别
      description: 新增产品价格类别
      parameters:
        - name: CategoryAddRequest
          in: body
          description: 价格类别属性
          schema:
            $ref: '#/definitions/categoryAddRequest'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true  
          type: string
      tags:
        - categories    
      responses:
        '201':
          description: 添加成功
        default:
          description: 添加失败
          schema:
            $ref: '#/definitions/Error'    
    get:
      summary: 查询分类列表
      description: 查询分类列表
      parameters:
        - name: size
          in: query
          default: 20
          description: 每页数量(默认20)
          required: true
          type: number
        - name: page
          in: query
          description: 当前页
          required: false
          type: number
        - name: nextId
          in: query
          description: 下一页ID
          required: false
          type: string
        - name: previousId
          in: query
          description: 上一页ID
          required: false
          type: string
      tags:
        - categories
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/categories'
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
  /ppcategories/{id}/path:
    get:
      summary: 某一分类的父层级
      description: 某一分类的父层级
      parameters:
        - name: id
          in: path
          type: string
          description: 分类ID
          required: true
          format: uuid
      tags:
        - categories    
      responses: 
        '200':
          description:  查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/category'
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'      
  /ppcategories/{id}:
    post:
      summary: 添加某分类的子分类
      description: 添加某分类的子分类
      parameters:
        - name: id
          in: path
          type: string
          description: 分类ID
          required: true
          format: uuid
        - name: CategoryAddRequest
          in: body
          description: 分类属性
          schema:
            $ref: '#/definitions/categoryAddRequest'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true  
          type: string  
      tags:
        - categories    
      responses:
        '201':
          description: 添加成功
        default:
          description: 添加失败
          schema:
            $ref: '#/definitions/Error'  
    get:
      summary: 查询分类
      description: 查询分类
      parameters:
        - name: id
          in: path
          type: string
          description: 分类ID
          required: true
          format: uuid
      tags:
        - categories    
      responses: 
        '200':
          description:  查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/categoryResponse'
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'      

    patch:
      summary: 修改某分类
      description: 修改某分类
      parameters:
        - name: id
          in: path
          type: string
          description: 分类ID
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true  
          type: string   
        - name: categoryUpdateRequest
          in: body
          description: 可修改属性
          schema:
            $ref: '#/definitions/categoryUpdateRequest'
          required: true
      tags:
        - categories    
      responses:
        '200':
          description: 修改成功
        default:
          description: 修改失败
          schema:
            $ref: '#/definitions/Error'  
    delete:
      summary: 删除某分类
      description: 删除某分类
      parameters:
        - name: id
          in: path
          type: string
          description: 分类ID
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true  
          type: string
      tags:
        - categories    
      responses:
        '200':
          description: 删除成功
        default:
          description: 删除失败
          schema:
            $ref: '#/definitions/Error'
  /ppcategories/{id}/children:
    get:
      summary: 查询某分类的子分类
      description: 查询某分类的子分类
      parameters:
        - name: id
          in: path
          type: string
          description: 分类ID
          required: true
          format: uuid
        - name: size
          in: query
          description: 每页个数(默认20)
          required: true
          type: number
        - name: page
          in: query
          description: 当前页
          required: false
          type: number
        - name: nextId
          in: query
          description: 下一页ID
          required: false
          type: string
        - name: previousId
          in: query
          description: 上一页ID
          required: false
          type: string
      tags:
        - categories
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/categories'
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'          
definitions:
  productprices:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: 下一页url
          self:
            properties:
              href:
                type: string
                description: 当前页url
          prev:
            properties:
              href:
                type: string
                description: 上一页url
      _embedded:
        properties:
          productpriceResponses:
            type: array
            items:
              $ref: '#/definitions/productpriceResponse'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: page total
  productpriceResponse:
    properties:
      id:
        type: string
        description: id of productPrice.
      productid:
        type: string
        description: productid of productPrice.
      productname:
        type: string
        description: productname of productPrice.
      price:
        type: string
        description: price of productPrice.
      companyid:
        type: string
        description: companyid of productPrice.
      companyname:
        type: string
        description: companyname of productPrice.
      categroyid:
        type: string
        description: categroyid of productPrice.
      categroyname:
        type: string
        description: categroyname of productPrice.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: The current page.
  productpriceByIdResponse:
    properties:
      id:
        type: string
        description: id of productPrice.
      productid:
        type: string
        description: productid of productPrice.
      productname:
        type: string
        description: productname of productPrice.
      price:
        type: string
        description: price of productPrice.
      companyid:
        type: string
        description: companyid of productPrice.
      companyname:
        type: string
        description: companyname of productPrice.
      categroyid:
        type: string
        description: categroyid of productPrice.
      categroyname:
        type: string
        description: categroyname of productPrice.
  addproductprice:
    properties:
      productId:
        type: string
        description: productId of productPrice.
      price:
        type: string
        description: price of productPrice.
      companyId:
        type: string
        description: companyid of productPrice.
      categroyId:
        type: string
        description: categroyid of productPrice.
  updateproductprice:
    properties:
      price:
        type: string
        description: price of productPrice.
  categories:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: next page url.
          self:
            properties:
              href:
                type: string
                description: current page url.
          prev:
            properties:
              href:
                type: string
                description: previous page url.
      _embedded:
        properties:
          categoryResponses:
            type: array
            items:
              $ref: '#/definitions/category'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data totalElements
          totalPages:
            type: string
            description: page totalPages
          number:
            type: string
            description: page number
  categoryResponse:
    properties:
      id:
        type: string
        description: id of product.
      name:
        type: string
        description: name of product.
      createTime:
        type: string
        description: createTime of category.
      companyId:
        type: string
        description: companyId of category.
      description:
        type: string
        description: description of category.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: current detail url.
          parent:
           properties:
              href:
                type: string
                description: Category parent detail url.
          children:
           properties:
              href:
                type: string
                description: Category children detail url.
  category:
    properties:
      id:
        type: string
        description: id of category.
      name:
        type: string
        description: name of category.
      createTime:
        type: string
        description: createTime of category.
      description:
        type: string
        description: description of category.
      _links:
        properties:
          self:
           properties:
              href:
                type: string
                description: current detail url.
  categoryAddRequest:
    properties:
      name:
        type: string
        description: name of category.
      companyId:
        type: string
        description: companyId of category.
      description:
        type: string
        description: description of category.
  categoryUpdateRequest:
    properties:
      name:
        type: string
        description: name of category.
      description:
        type: string
        description: description of category.      
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
