swagger: '2.0'
info:
  title: Product Price
  description: Product price application API 
  version: 1.0.0
host: '103.245.129.20:8087'
schemes:
  - http
basePath: /
produces:
  - application/hal+json
paths:
  /productprices/search:
    get:
      summary: 查询产品价格服务.
      description: 多条件查询产品价格服务.
      parameters:
        - name: keyword
          in: query
          description: 产品名称(productName)查询,支持模糊查询.
          required: false
          type: string
        - name: catgoryId
          in: query
          description: 根据产品价格分类查询.
          required: false
          type: string
        - name: productCategoryId
          in: query
          description: 根据产品分类查询.
          required: false
          type: string
        - name: productId
          in: query
          description: 根据产品Id查询.
          required: false
          type: string
        - name: bevel
          in: query
          default: '5'
          description: 位置直径(单位为公里,默认是5公里).
          required: false
          type: string
          format: double
        - name: lat
          in: query
          description: 地理位置查询(中心点的纬度).
          required: true
          type: string
          format: double
        - name: lon
          in: query
          description: 地理位置查询(中心点的经度).
          required: true
          type: string
          format: double
      tags:
        - productprices
      responses:
        '201':
          description: 查询成功.
          schema:
            type: string
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
  /productprices/search/products:
    get:
      summary: 查询产品服务价格并根据产品分组.
      description: 查询产品服务价格并根据产品分组.
      parameters:
        - name: keyword
          in: query
          description: 产品名称(productName)查询,支持模糊查询.
          required: false
          type: string
        - name: catgoryId
          in: query
          description: 根据产品价格分类查询.
          required: false
          type: string
        - name: productCategoryId
          in: query
          description: 根据产品分类查询.
          required: false
          type: string
        - name: bevel
          in: query
          default: '5'
          description: 位置直径(单位为公里,默认是5公里).
          required: false
          type: string
          format: double
        - name: lat
          in: query
          description: 地理位置查询(中心点的纬度).
          required: true
          type: string
          format: double
        - name: lon
          in: query
          description: 地理位置查询(中心点的经度).
          required: true
          type: string
          format: double
      tags:
        - productprices
      responses:
        '201':
          description: 查询成功.
          schema:
            type: string
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
            
  /productprices:
    post:
      consumes:
        - application/vnd.jiahua.commands.copyproduct+json
      summary: 增加一个产品价格服务
      description: 新增产品价格服务
      parameters:
        - name: addproductprice
          in: body
          description: The productPrice JSON you want to post
          schema:
            $ref: '#/definitions/addproductprice'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: X-Token is a request header and is required.
          required: true
          type: string
      tags:
        - productprices
      responses:
        '200':
          description: 添加成功
          schema:
            type: string
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 添加失败
          schema:
            $ref: '#/definitions/Error'
    get:
      summary: 查询产品服务列表
      description: 查询产品服务列表.
      parameters:
        - name: page
          in: query
          default: 0
          description: 分页参数
          required: false
          type: number
          format: int
        - name: size
          in: query
          default: 20
          description: 每页的数量(默认20)
          required: false
          type: number
          format: int
        - name: nextId
          in: query
          description: 下一页ID
          required: false
          type: string
        - name: previousId
          in: query
          description: 上一页ID.
          required: false
          type: string
      tags:
        - productprices
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/productprices'
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
  /productprices/selfdefine:
    post:
      consumes:
        - application/vnd.jiahua.commands.selfdefine+json
      summary: 增加一个自定义的产品价格服务
      description: 新增自定义的产品价格服务
      parameters:
        - name: addproductprice
          in: body
          description: The productPrice JSON you want to post
          schema:
            $ref: '#/definitions/addSelfProductPrice'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: X-Token is a request header and is required.
          required: true
          type: string
      tags:
        - productprices
      responses:
        '200':
          description: 添加成功
          schema:
            type: string
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 添加失败
          schema:
            $ref: '#/definitions/Error'
  '/productprices/{id}':
    get:
      summary: 根据ID查询产品服务
      description: 根据ID查询产品服务
      parameters:
        - name: id
          in: path
          type: string
          description: 产品服务ID
          required: true
          format: uuid
      tags:
        - productprices    
      responses:
        '200':
          description: 查询成功
          schema:
            type: array
            items:
              $ref: '#/definitions/productpriceByIdResponse'
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 查询失败
          schema:
            $ref: '#/definitions/Error'
    patch:
      consumes:
        - application/vnd.jiahua.commands.updateProductPrice+json
      summary: 修改产品服务
      description: 修改产品服务
      parameters:
        - name: id
          in: path
          description: 产品服务ID
          required: true
          type: string
          format: uuid
        - name: updateproductprice
          in: body
          description: 可以修改的参数,在request body中
          schema:
            $ref: '#/definitions/updateproductprice'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true
          type: string 
      tags:
        - productprices    
      responses:
        '200':
          description: 修改成功
          schema:
            type: string
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 修改失败
          schema:
            $ref: '#/definitions/Error'
    delete:
      consumes:
        - application/vnd.jiahua.commands.deleteProductPrice+json
      summary: 删除产品价格
      description: 删除产品价格
      parameters:
        - name: id
          in: path
          description: 产品价格ID
          required: true
          type: string
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: 登录认证
          required: true
          type: string
      tags:
        - productprices  
      responses:
        '200':
          description: 删除成功
          schema:
            type: string
        '401':
          description: 没有访问权限.
          schema:
            type: string
        default:
          description: 删除失败
          schema:
            $ref: '#/definitions/Error'
definitions:
  productprices:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: 下一页url
          self:
            properties:
              href:
                type: string
                description: 当前页url
          prev:
            properties:
              href:
                type: string
                description: 上一页url
      _embedded:
        properties:
          productpriceResponses:
            type: array
            items:
              $ref: '#/definitions/productpriceResponse'
      page:
        properties:
          size:
            type: string
            description: 分页大小
          totalElements:
            type: string
            description: 数据总条数
          totalPages:
            type: string
            description: 总分页大小
          number:
            type: string
            description: 当前页值
  productpriceResponse:
    properties:
      uuid:
        type: string
        description: 产品价格ID
      productid:
        type: string
        description: 产品ID
      productname:
        type: string
        description: 产品名称
      price:
        type: string
        description: 价格
      companyid:
        type: string
        description: 公司ID
      companyname:
        type: string
        description: 公司名称
      categroyid:
        type: string
        description: 分类ID
      categroyname:
        type: string
        description:  分类名称
      icon:
        type: string
        description:  图片ID
      description:
        type: string
        description:  价格描述
      status:
        type: string
        description:  状态
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: 当前页链接
  productpriceByIdResponse:
    properties:
      uuid:
        type: string
        description: 产品价格ID
      productId:
        type: string
        description: 产品ID
      productname:
        type: string
        description: 产品名称
      price:
        type: string
        description: 价格
      companyId:
        type: string
        description: 公司ID
      companyname:
        type: string
        description: 公司名称
      categroyId:
        type: string
        description: 分类ID
      categroyname:
        type: string
        description:  分类名称
      unit:
        type: string
        description:  单位
      icon:
        type: string
        description:  图片ID
      description:
        type: string
        description:  价格描述
      status:
        type: string
        description:  状态
      location:
        properties:
          lon:
            type: string
            description: 经度
          lat:
            type: string
            description: 纬度
      createdTime:
        type: string
        description:  创建时间
      createdBy:
        type: string
        description:  创建人
      modifiedTime:
        type: string
        description:  修改时间
      modifiedBy:
        type: string
        description:  修改人
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: 当前页链接
  addproductprice:
    properties:
      productId:
        type: string
        description: 产品ID
      price:
        type: string
        description: 产品价格
      unit:
        type: string
        description: 单位.
      companyId:
        type: string
        description: 公司ID
      categroyId:
        type: string
        description: 分类ID（默认分类为全部，非必填）
  addSelfProductPrice:
    properties:
      productName:
        type: string
        description: 产品名称
      price:
        type: string
        description: 产品价格
      unit:
        type: string
        description: 单位.
      companyId:
        type: string
        description: 公司ID
      categroyId:
        type: string
        description: 分类ID（默认分类为全部，非必填）
  updateproductprice:
    properties:
      categroyId:
        type: string
        description: 产品分类ID（默认分类为全部，非必填）
      price:
        type: string
        description: 产品价格
      status:
        type: string
        description: 产品上下架状态
      description:
        type: string
        description: 产品价格描述
      lat:
        type: string
        description: 产品位置信息（纬度）
      lon:
        type: string
        description: 产品位置信息（经度）

  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string