swagger: '2.0'
info:
  title: terminal rest
  description:  终端管理 
  version: 1.0.0
host: '103.245.129.20:8087'
schemes:
  - http
produces:
  - application/json
paths:
  /cp150s/{imei}/locations:
    get:
      summary: 终端轨迹 API.
      description:
        终端轨迹 API.
      parameters:
        - name: imei
          in: path
          type: string
          description: .
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 终端管理
      responses:
        '200':
          description: 查询成功.
          description: Unexpected error
          schema:
            $ref: '#/definitions/locationsResponse'
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'           
 
 
        
definitions:
  locationsResponse:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        type: array
        items:
          $ref: '#/definitions/locations'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: current page 

  locations:
    properties:
      date:
        type: string
      longitude:
        type: string
      latitude:
        type: string
  Error:
    properties:
      entity:
        type: string
      message:
        type: string
      invalidValue:
        type: string
      property:
        type: string
