swagger: '2.0'
info:
  title: User Location
  description: Move your app forward with the Location Search API 
  version: 1.0.0
host: '103.245.128.220:8087'
schemes:
  - http
produces:
  - application/hal+json
paths:
  /userlocationserver/users/latestlocations/byfence:
    get:
      summary: 查询最近在电子围栏中的所有用户列表.
      description: 查询最近在电子围栏中的所有用户列表.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: topLeftLat
          in: query
          description: 矩形电子围栏左上角点的纬度.
          required: true
          type: string
          format: double      
        - name: topLeftLon
          in: query
          description: 矩形电子围栏左上角点的经度.
          required: true
          type: string
          format: double
        - name: bottomRightLat
          in: query
          description: 矩形电子围栏右下角点的纬度.
          required: true
          type: string
          format: double
        - name: bottomRightLon
          in: query
          description: 矩形电子围栏右下角点的经度.
          required: true
          type: string
          format: double 
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
          format: int
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
          format: int
      tags:
        - 用户位置第二部分 
      responses:
        '200':
          description: return status code after find user location success.
          schema:
            $ref: '#/definitions/usersLatestLocation'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      
  /userlocationserver/users/{userId}/historylocations/bytime:
    get:
      summary: 查询某个用户某个时间段的历史轨迹.
      description: 查询某个用户某个时间段的历史轨迹.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: userId
          in: path
          description: 用户ID.
          required: true
          type: string
        - name: start
          in: query
          description: 查询开始时间(例如:"2015-08-15T02:03:05").
          required: false
          type: string
        - name: end
          in: query
          description: 查询结束时间(例如:"2015-08-20T02:03:05").
          required: false
          type: string
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
          format: int
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
          format: int      
      tags:
        - 用户位置第二部分 
      responses:
        '200':
          description: return status code after find user location success.
          schema:
            $ref: '#/definitions/userLocations'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
              
  /userlocationserver/users/{userId}/locationsubscribers:
    get:
      summary: 用户(userId)位置的订阅者列表.
      description:
        用户(userId)位置的订阅者列表.
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
        - name: nextId
          in: query
          description: 下一个页需要当前页的id.
          required: false
          type: string
        - name: previousId
          in: query
          description: 前一页需要当前页面的第一个id.
          required: false
          type: string
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户位置订阅关系第二部分
      responses:
        '200':
          description: 查询成功.
          schema:
            type: array
            items:
              $ref: '#/definitions/subscribers'
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'
            
  /userlocationserver/users/{userId}/locationsubscribers/{subscriberId}:
    get:
      summary: 用户(userId)位置的订阅者(subscriberId)详情.
      description:
        用户(userId)位置的订阅者(subscriberId)详情.
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: subscriberId
          in: path
          type: string
          description: 订阅者ID.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户位置订阅关系第二部分
      responses:
        '200':
          description: 查询成功.
          schema:
            type: array
            items:
              $ref: '#/definitions/subscribersDetails'
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: 删除用户(userId)位置的订阅者(subscriberId).
      description: 删除用户(userId)位置的订阅者(subscriberId).
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: subscriberId
          in: path
          type: string
          description: 订阅者ID.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户位置订阅关系第二部分
      responses:
        '200':
          description: locationsubscribers deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /userlocationserver/mysettings:
    patch:
        summary: 修改个人设置中的百度通道ID.
        description:
          修改个人设置中的百度通道ID.
        parameters:
          - name: channel
            in: body
            description: The channel id JSON you want to post.
            schema:
               $ref: '#/definitions/addMysettings'
            required: true
          - name: X-Token
            in: header
            default: '{X-Token}'
            description: Oauth token code.
            required: true
            type: string
            format: double
        tags:
         - 用户位置订阅关系第一部分
        responses:
          '200':
           description: 修改个人设置中的百度通道ID成功.            
            
  /userlocationserver/users/{userId}/locationobservables:
    post:
      summary: 添加用户(userId)的订阅对象.
      description:
        添加用户(userId)的订阅对象.
      consumes:
        - application/vnd.jiahua.commands.onoffsome+json
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: observables
          in: body
          description: 被观察者数组.
          schema:
            type: array
            items:
             $ref: '#/definitions/addMyobservables'
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户位置订阅关系第一部分
      responses:
        '201':
          description: 添加用户(userId)的订阅对象    
    get:
      summary: 用户(userId)的订阅对象列表.
      description:
        用户(userId)的订阅对象列表.
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户位置订阅关系第一部分
      responses:
        '200':
          description: subscribers page list
          schema:
            type: array
            items:
              $ref: '#/definitions/myobservablesDetails'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /userlocationserver/users/{userId}/locationobservables/latestlocations:
    get:
      summary: 查询用户(userId)的订阅对象最后一次位置信息.
      description:
        查询用户(userId)的订阅对象最后一次位置信息.
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户位置第二部分 
      responses:
        '200':
          description: 查询用户(userId)的订阅对象最后一次位置信息成功.
          schema:
            $ref: '#/definitions/usersLatestLocation'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'           
  /mylocations:
    post:
      summary: 上传位置更新.
      description:
        上传位置更新.
      parameters:
        - name: locationAddRequest
          in: body
          description: 当前用户位置的经纬度.
          schema:
             $ref: '#/definitions/locationAddRequest'
          required: true
      tags:
       - 用户位置第一部分
      responses:
        '202':
         description: 接受上传位置更新.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  

definitions:
  userLocations:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        properties:
          userLocationResponses:
            type: array
            items:
              $ref: '#/definitions/getUserLocation'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: current page 
 
  usersLatestLocation:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        properties:
          userLocationResponses:
            type: array
            items:
              $ref: '#/definitions/getUserLatestLocation'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: current page 
            
  getUserLocation:
    properties:
      uuid:
        type: string
        description:  uuid of user location.
      updatedTime:
        type: string
        description:  updatedTime of user.
      location:
        properties:
          lat:
            type: string
            description:  lat of user.
          lon:
            type: string
            description:  lon of user.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: get current user location information url link.
                
  getUserLatestLocation:
    properties:
      name:
        type: string
        description:  name of user.
      userId:
        type: string
        description:  id of user.
      updatedTime:
        type: string
        description:  updatedTime of user.
      location:
        properties:
          lat:
            type: string
            description:  lat of user.
          lon:
            type: string
            description:  lon of user.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: get current user location information url link.   
  subscribers:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: next page url.
          self:
            properties:
              href:
                type: string
                description: current page url.
          prev:
            properties:
              href:
                type: string
                description: previous page url.
      _embedded:
        properties:
          uuid:
            type: string
            description: Id of subscribers.
          push:
            type: string
            description: Whether to receive a message.
          subscriberId:
            type: string
            description: Id of subscribers.
          createdTime:
            type: string
            description: Created time of subscribers.
          _links:
            properties:
              self:
                properties:
                  href:
                    type: string
                    description: The current page.
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: page total
  myobservablesDetails:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: next page url.
          self:
            properties:
              href:
                type: string
                description: current page url.
          prev:
            properties:
              href:
                type: string
                description: previous page url.
      _embedded:
        properties:
          uuid:
            type: string
            description: Id of subscribers.
          observableId:
            type: string
            description: 被观察者ID.
          loginName:
            type: string
            description: 被观察者名字.
          push:
            type: string
            description: Whether to receive a message.
          createdTime:
            type: string
            description: Created time of subscribers.
          _links:
            properties:
              self:
                properties:
                  href:
                    type: string
                    description: The current page.
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: page total          
  subscribersDetails:
    properties:
        uuid:
            type: string
            description: Id of subscribers.
        push:
          type: string
          description: Whether to receive a message.
        subscriberId:
          type: string
          description: Id of subscribers.
        createdTime:
          type: string
          description: Created time of subscribers.
  addMysettings:
    properties:
        channelId:
          type: string
          description: 百度通道ID.
  addMyobservables:
    properties:
       observableId:
         type: string
         description: 被观察者uuid。
       loginName:
         type: string
         description: 被观察者名字.
       push:
         type: string
         description: push(ON or OFF).
              
  locationAddRequest:
    properties:
      lat:
        type: string
        description: 纬度.
      lon:
        type: string
        description: 经度.
      type:
        type: string
        description: 经纬度类型.如bd09ll（百度经纬度坐标）、bd09mc（百度摩卡托坐标）、gcj02（国测局加密坐标）、wgs84（gps设备获取的坐标）.

  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
