swagger: '2.0'
info:
  title: User Location
  description: Move your app forward with the Location Search API 
  version: 1.0.0
host: '103.245.128.220:8087'
schemes:
  - http
produces:
  - application/json
paths:
  /mylocations:
    get:
      summary: 查询用户自己某天的位置轨迹信息.
      description:
        查询用户自己某天的位置轨迹信息.
      parameters:
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
        - name: updatedDate
          in: query
          description: 查询日期(例如：2015-08-15).
          required: false
          type: string
      tags:
        - 用户位置第二部分
      responses:
        '200':
          description: locations page list
          schema:
            type: array
            items:
              $ref: '#/definitions/userLocations'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{userId}/locations:
    get:
      summary: 查询某个用户某个日期的位置轨迹信息
      description:
        查询某个用户某个日期的位置轨迹信息.
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
        - name: updatedDate
          in: query
          description: 查询日期(例如:2015-08-15).
          required: false
          type: string
      tags:
        - 用户位置第二部分
      responses:
        '200':
          description: locations page list
          schema:
            type: array
            items:
              $ref: '#/definitions/userLocations'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/lastestlocation/byfence:
    get:
      summary: 查询最近在电子围栏中的所有用户列表.
      description: 查询最近在电子围栏中的所有用户列表.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: topLeftLat
          in: query
          description: 矩形电子围栏左上角点的纬度.
          required: true
          type: string
          format: double      
        - name: topLeftLon
          in: query
          description: 矩形电子围栏左上角点的经度.
          required: true
          type: string
          format: double
        - name: bottomRightLat
          in: query
          description: 矩形电子围栏右下角点的纬度.
          required: true
          type: string
          format: double
        - name: bottomRightLon
          in: query
          description: 矩形电子围栏右下角点的经度.
          required: true
          type: string
          format: double 
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
          format: int
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
          format: int
      tags:
        - 用户位置第二部分 
      responses:
        '200':
          description: return status code after find user location success.
          schema:
            $ref: '#/definitions/usersLastestLocation'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /users/{userId}/history/bytime:
    get:
      summary: 查询某个用户某个时间段的历史轨迹.
      description: 查询某个用户某个时间段的历史轨迹.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: userId
          in: path
          description: 用户ID.
          required: true
          type: string
        - name: start
          in: query
          description: 查询开始时间(例如:"2015-08-15T02:03:05").
          required: false
          type: string
        - name: end
          in: query
          description: 查询结束时间(例如:"2015-08-20T02:03:05").
          required: false
          type: string
        - name: page
          in: query
          description: 显示第几页.
          required: false
          type: number
          format: int
        - name: size
          in: query
          description: 每页显示多少条数据.
          required: false
          type: number
          format: int      
      tags:
        - 用户位置第二部分 
      responses:
        '200':
          description: return status code after find user location success.
          schema:
            $ref: '#/definitions/userLocations'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'   
                  
definitions:
  userLocations:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        properties:
          userLocationResponses:
            type: array
            items:
              $ref: '#/definitions/getUserLocation'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: current page 
 
  usersLastestLocation:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: query next page url.
          self:
            properties:
              href:
                type: string
                description: query self page url.
          prev:
            properties:
              href:
                type: string
                description: query previous page url.
      _embedded:
        properties:
          userLocationResponses:
            type: array
            items:
              $ref: '#/definitions/getUserLastestLocation'
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: current page 
            
  getUserLocation:
    properties:
      uuid:
        type: string
        description:  uuid of user location.
      updatedTime:
        type: string
        description:  updatedTime of user.
      location:
        properties:
          lat:
            type: string
            description:  lat of user.
          lon:
            type: string
            description:  lon of user.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: get current user location information url link.
                
  getUserLastestLocation:
    properties:
      name:
        type: string
        description:  name of user.
      userId:
        type: string
        description:  id of user.
      updatedTime:
        type: string
        description:  updatedTime of user.
      location:
        properties:
          lat:
            type: string
            description:  lat of user.
          lon:
            type: string
            description:  lon of user.
      _links:
        properties:
          self:
            properties:
              href:
                type: string
                description: get current user location information url link.   
  subscribers:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: next page url.
          self:
            properties:
              href:
                type: string
                description: current page url.
          prev:
            properties:
              href:
                type: string
                description: previous page url.
      _embedded:
        properties:
          uuid:
            type: string
            description: Id of subscribers.
          push:
            type: string
            description: Whether to receive a message.
          subscriberId:
            type: string
            description: Id of subscribers.
          createdTime:
            type: string
            description: Created time of subscribers.
          _links:
            properties:
              self:
                properties:
                  href:
                    type: string
                    description: The current page.
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: page total
  myobservablesDetails:
    properties:
      _links:
        properties:
          next:
            properties:
              href:
                type: string
                description: next page url.
          self:
            properties:
              href:
                type: string
                description: current page url.
          prev:
            properties:
              href:
                type: string
                description: previous page url.
      _embedded:
        properties:
          uuid:
            type: string
            description: Id of subscribers.
          observablesId:
            type: string
            description: Id of observables.
          push:
            type: string
            description: Whether to receive a message.
          createdTime:
            type: string
            description: Created time of subscribers.
          _links:
            properties:
              self:
                properties:
                  href:
                    type: string
                    description: The current page.
      page:
        properties:
          size:
            type: string
            description: page size
          totalElements:
            type: string
            description: data total
          totalPages:
            type: string
            description: page total
          number:
            type: string
            description: page total          
  subscribersDetails:
    properties:
        uuid:
            type: string
            description: Id of subscribers.
        push:
          type: string
          description: Whether to receive a message.
        subscriberId:
          type: string
          description: Id of subscribers.
        createdTime:
          type: string
          description: Created time of subscribers.
  addMysettings:
    properties:
        channelId:
          type: string
          description: Baidu to push channel ID.
  addMyobservables:
    properties:
       observablesId:
         type: string
         description: Observables id.
       push:
         type: string
         description: push(ON or OFF).
              
  addOnoffall:
    properties:
        push:
          type: string
          description: push(ON or OFF). 
  locationAddRequest:
    properties:
      lat:
        type: string
        description: 纬度.
      lon:
        type: string
        description: 经度.
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
