swagger: '2.0'
info:
  title: user rest
  description: 用户管理 
  version: 1.0.0
host: '103.245.129.20:8087'
schemes:
  - http
produces:
  - application/json
paths:
  /terminalusers:
    post:
      summary: 添加终端用户（老人用户）API.
      description:
        添加终端用户（老人用户）API.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: addTerminalusersRequest
          in: body
          description: 添加终端用户（老人用户）body.
          schema:
             $ref: '#/definitions/addTerminalusersRequest'
          required: true
      tags:
       - 用户管理
      responses:
        '201':
         description: 添加终端用户（老人用户）成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  
            
  /terminalusers/{uuid}:
    patch:
      summary: 修改终端用户（老人用户）API.
      description:
        修改终端用户（老人用户）API.
      parameters:
        - name: uuid
          in: path
          type: string
          description:  .
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: addTerminalusersRequest
          in: body
          description: 修改终端用户（老人用户）body.
          schema:
             $ref: '#/definitions/addTerminalusersRequest'
          required: true
      tags:
       - 用户管理
      responses:
        '204':
          description: 修改终端用户（老人用户）成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  
    get:
      summary: 终端用户（老人）详情API.
      description:
        终端用户（老人）详情API.
      parameters:
        - name: uuid
          in: path
          type: string
          description: .
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户管理
      responses:
        '200':
          description: 查询成功.
          schema:
            type: array
            items:
              $ref: '#/definitions/terminaluserDetails'
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'
            
  /terminalusers/search/findByTerminalImeiAndTerminalCheckCode:
    get:
      summary: 根据imei&checkcode查询终端用户（老人）API.
      description:
        根据imei&checkcode查询终端用户（老人）API.
      parameters:
        - name: imei
          in: query
          type: string
          description: .
          required: true
        - name: checkcode
          in: query
          type: string
          description: .
          required: true
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户管理
      responses:
        '200':
          description: 查询成功.
          description: Unexpected error
          schema:
            $ref: '#/definitions/_embedded' 
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'

  /users/register:            
    post:
      summary: （子女端）用户注册API.
      description:
        （子女端）用户注册API.
      consumes:
        - application/vnd.jiahua.commands.registerUser.v1+json
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: registerRequest
          in: body
          description: 添加（子女端）用户注册body.
          schema:
             $ref: '#/definitions/registerRequest'
          required: true
      tags:
       - 用户管理
      responses:
        '201':
         description: 添加（子女端）用户注册成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'            
  
  /users/{userId}/addterminal:            
    post:
      summary: 用户绑定终端（子女绑定终端老人用户）API.
      description:
        用户绑定终端（子女绑定终端老人用户）API.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: addterminalRequest
          in: body
          description: 添加用户绑定终端body.
          schema:
             $ref: '#/definitions/addterminalRequest'
          required: true
      tags:
       - 用户管理
      responses:
        '201':
         description: 添加用户绑定终端成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  
            
            
  /users/{userId}/boundedTerminals:
    get:
      summary: 用户绑定终端（子女绑定终端老人用户）列表API.
      description:
        用户绑定终端（子女绑定终端老人用户）列表API.
      parameters:
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户管理
      responses:
        '200':
          description: 查询成功.
          description: Unexpected error
          schema:
            type: array
            items:
              $ref: '#/definitions/boundedTerminals'
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'           
 
  /users/{userId}/updateterminal:            
    post:
      summary: 用户（子女）修改终端用户（老人）昵称API.
      description:
        用户（子女）修改终端用户（老人）昵称API.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
        - name: updateterminal
          in: body
          description: 用户（子女）修改终端用户（老人）昵称body.
          schema:
             $ref: '#/definitions/updateterminalRequest'
          required: true
      tags:
       - 用户管理
      responses:
        '201':
         description: 用户（子女）修改终端用户（老人）昵称成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  
            
  /users/{userId}/deleteterminal:            
    post:
      summary: 用户（子女）解除终端用户（老人）绑定API.
      description:
        用户（子女）解除终端用户（老人）绑定API.
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
          required: true
        - name: boundedId
          in: body
          description: 用户（子女）解除终端用户（老人）绑定body.
          schema:
             properties:
                boundedId:
                  type: string
                  description: .
      tags:
       - 用户管理
      responses:
        '200':
         description: 用户（子女）解除终端用户（老人）绑定成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
           
  /users/search:
    get:
      summary: 用户(子女端)详情API.
      description:
        用户(子女端)详情API.
      parameters:
        - name: loginname
          in: query
          type: string
          description: .
          required: true
          format: uuid
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
      tags:
        - 用户管理
      responses:
        '200':
          description: 查询成功.
          description: Unexpected error
          schema:
            $ref: '#/definitions/userdetails'
        default:
          description: 查询错误.
          schema:
            $ref: '#/definitions/Error'            
         
  /users/{userId}/passwordupdate:            
    post:
      summary: 修改用户(子女端)信息API.
      description:
        修改用户(子女端)信息API.
      consumes:
        - application/vnd.jiahua.commands.updateNormalUser.v1+json
      parameters:
        - name: X-Token
          in: header
          default: '{X-Token}'
          description: Oauth token code.
          required: true
          type: string
          format: double
        - name: userId
          in: path
          type: string
          description: 用户ID.
          required: true
          format: uuid
          required: true
        - name: passwordupdate
          in: body
          description: 修改用户(子女端)信息body.
          schema:
            $ref: '#/definitions/passwordupdate'
      tags:
       - 用户管理
      responses:
        '200':
         description: 修改用户(子女端)信息成功.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'        
         
        
definitions:
  addTerminalusersRequest:
    properties:
      terminalImei:
        type: string
        description: .
      terminalCheckCode:
        type: string
        description: .
      avatar:
        type: string
        description: .
      gender:
        type: string
        description: .
      birthday:
        type: string
        description: .
      address:
        type: string
        description: .
      cityCode:
        type: string
        description: .
      remarks:
        type: string
        description: .
      telNum:
        type: string
        description: .
      realName:
        type: string
        description: .
      nickName:
        type: string
        description: .
      height:
        type: string
        description: .
      weight:
        type: string
        description: .
      bloodType:
        type: string
        description: .
      sbp:
        type: string
        description: .
      dbp:
        type: string
        description: .
      healthStatus:
        type: string
        description: .
      drugAllergy:
        type: string
        description: .
        
  _embedded:
    properties:
      terminalusers:
        type: array
        items:
          properties:
            terminalImei:
              type: string
              description: .
            terminalCheckCode:
              type: string
              description: .
            avatar:
              type: string
              description: .
            gender:
              type: string
              description: .
            birthday:
              type: string
              description: .
            address:
              type: string
              description: .
            cityCode:
              type: string
              description: .
            remarks:
              type: string
              description: .
            telNum:
              type: string
              description: .
            realName:
              type: string
              description: .
            nickName:
              type: string
              description: .
            height:
              type: string
              description: .
            weight:
              type: string
              description: .
            bloodType:
              type: string
              description: .
            sbp:
              type: string
              description: .
            dbp:
              type: string
              description: .
            healthStatus:
              type: string
              description: .
            drugAllergy:
              type: string
              description: .
            _links:
              properties:
                self:
                  properties:
                    href:
                      type: string
                      description: .
  registerRequest:
    properties:   
        loginName :
          type: string
          description: .
        nickName :
          type: string
          description: .
        terminalUserNickName :
          type: string
          description: .
        password :
          type: string
          description: .
        tel :
          type: string
          description: .
        email :
          type: string
          description: .
        gender :
          type: string
          description: .
        birthDay :
          type: string
          description: .
        cityCode :
          type: string
          description: .
        address :
          type: string
          description: .
        terminalUserUuid :
          type: string
          description: .
          
  addterminalRequest:
    properties:   
      nickName :
          type: string
          description: .
      terminalUserId :
        type: string
        description: .  
        
  boundedTerminals:
    properties:
      id:
        type: string
        description: .
      terminalUserId:
        type: string
        description: .
      terminalId:
        type: string
        description: .
      nickName:
        type: string
        description: .
      imei:
        type: string
        description: .
      sim:
        type: string
        description: .
      activateTime:
        type: string
        description: .
      status:
        type: string
        description: .

  updateterminalRequest:
    properties:   
      boundedId :
          type: string
          description: .
      nickName :
        type: string
        description: .  
        
  terminaluserDetails:
      properties:
          terminalImei:
            type: string
            description: .
          terminalCheckCode:
            type: string
            description: .
          avatar:
            type: string
            description: .
          gender:
            type: string
            description: .
          birthday:
            type: string
            description: .
          address:
            type: string
            description: .
          cityCode:
            type: string
            description: .
          remarks:
            type: string
            description: .
          telNum:
            type: string
            description: .
          realName:
            type: string
            description: .
          nickName:
            type: string
            description: .
          height:
            type: string
            description: .
          weight:
            type: string
            description: .
          bloodType:
            type: string
            description: .
          sbp:
            type: string
            description: .
          dbp:
            type: string
            description: .
          healthStatus:
            type: string
            description: .
          drugAllergy:
            type: string
            description: .
          _links:
            properties:
              self:
                properties:
                  href:
                    type: string
                    description: . 
    
  userdetails:
      properties:
          loginName:
            type: string
            description: .
          type:
            type: string
            description: .
          email:
            type: string
            description: .
          tel:
            type: string
            description: .
          nickName:
            type: string
            description: .
          realName:
            type: string
            description: .
          createDate:
            type: string
            description: .
          profiles:
            type: array
            items:
              properties:
                pName:
                  type: string
                  description: .
                pValue:
                  type: string
                  description: .
                uuid:
                  type: string
                  description: .
          roles:
            type: array
            items:
              properties:
                name:
                  type: string
                  description: .
                description:
                  type: string
                  description: .
                uuid:
                  type: string
                  description: .
          permissions:
            type: array
            items:
              properties:
                name:
                  type: string
                  description: .
                module:
                  type: string
                  description: .
                description:
                  type: string
                  description: . 
                uuid:
                  type: string
                  description: .
         
          uuid:
            type: string
            description: .  
            
  passwordupdate:
    properties:   
      nickName :
        type: string
        description: .
      tel :
        type: string
        description: .
      email :
        type: string
        description: .
      gender :
        type: string
        description: .
      cityCode :
        type: string
        description: .
      address :
        type: string
        description: .
      birthDay :
        type: string
        description: .
  
                  
  Error:
    properties:
      entity:
        type: string
      message:
        type: string
      invalidValue:
        type: string
      property:
        type: string
